# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         capitalization
version:      0.03
version_from: capitalization.pm
installdirs:  site
requires:
    Devel::Symdump:                0
    Test::More:                    0.32

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
